### ISSUE TITLE
JavaBindings dont build with gnumake && python 3.12

### ISSUE THREAD

**Issue by Schmoho** [sbmlteam/libsbml#386]
Hey,

I do not know much about C compilation, so I am not perfectly sure this is not a system specific issue, but compilation fails for me:

```
/home/user/libsbml-5.20.2/doltlibtool --mode=compile --tag=CXX g++ -I. -I/home/user/libsbml-5.20.2/src -DLINUX    -I/usr/include/libxml2 -DUSE_LIBXML    -MT LibXMLParser.lo -MD -MP -MF ".deps/LibXMLParser.Po" -c -o LibXMLParser.lo LibXMLParser.cpp
LibXMLParser.cpp: In member function ‘virtual bool LibXMLParser::parseNext()’:
LibXMLParser.cpp:427:46: error: invalid conversion from ‘const xmlError*’ {aka ‘const _xmlError*’} to ‘xmlErrorPtr’ {aka ‘_xmlError*’} [-fpermissive]
  427 |     xmlErrorPtr libxmlError = xmlGetLastError();
      |                               ~~~~~~~~~~~~~~~^~
      |                                              |
      |                                              const xmlError* {aka const _xmlError*}
make[3]: *** [../../../config/makefile-common-actions.mk:301: LibXMLParser.lo] Error 1
make[3]: Leaving directory '/home/user/libsbml-5.20.2/src/sbml/xml'
make[2]: *** [../../config/makefile-common-actions.mk:373: xml-recurse] Error 2
make[2]: Leaving directory '/home/user/libsbml-5.20.2/src/sbml'
make[1]: *** [../config/makefile-common-actions.mk:373: sbml-recurse] Error 2
make[1]: Leaving directory '/home/user/libsbml-5.20.2/src'
make: *** [config/makefile-common-actions.mk:373: src-recurse] Error 2
make: Leaving directory '/home/user/libsbml-5.20.2'
``` 

[This documentation page](https://sbml.org/software/libsbml/libsbml-docs/api/java/) mentions one needs " libxml2 version 2.6.16 or later" which in principle is satisfied. To be honest, I have almost never seen a project that specifies "or later" for any dependency that still builds a year later, but I guess that is besides the point.

Am I correct in assuming that this indicates there is a version mismatch between libsbml and libxml2?

**Comment by fbergmann** [comment]
There was a breaking API change in libxml2, this has been since resolved in our codebase, and is available with release 5.20.4.

**Comment by Schmoho** [comment]
Sorry, you are right.

I encountered follow up problems however, maybe these are again just my incompetence or warrant a new issue, so I figured I'd ask here first:


First, the Java-version check seems to be broken:

```
checking /usr/bin/java version >= 1.5.0... no
configure: error: Need Java version 1.5.0, but only found version java version "17.0.12" 2024-07-16
```

Second, I still can't compile 5.20.4 with java bindings, because there seems to be a bug related to swigdoc:
```
/home/user/libsbml-5.20.4/src/bindings/swig/libsbmlutils.py:144: SyntaxWarning: invalid escape sequence '\s'
  match = re.search('%template\s*\(([^)]+)\)', line)
Traceback (most recent call last):
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 1933, in <module>
    main(sys.argv)
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 1890, in main
    processFile(file, stream, language, preprocessor_defines)
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 1701, in processFile
    header  = CHeader(istream, language, preprocessor_defines)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 202, in __init__
    read_loop(self.header_line_parser, stream.readlines(), defines)
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 621, in read_loop
    line_parser_func(line)
  File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 372, in header_line_parser
    func = Method(private, self.docstring, name, args, (isConst > 0),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/libsbml-5.20.4/src/bindings/java/../swig/swigdoc.py", line 470, in __init__
    if isConst and 'unsigned int' in args >= 0:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'
```
Since the latter might be related to my Python version (3.12.4)  I tried that with a bunch of other versions in conda and I got different variations of the same error message

**Comment by fbergmann** [comment]
would it be possible for you to compile using the cmake build system? We are phasing out the gnumake (./configure && make) build process in favor for it, and so you encounter some these issues. 

```bash
cmake -DWITH_JAVA=ON
``` 

that should succeed at least it did so in the [nightly build](https://github.com/sbmlteam/libsbml/actions/runs/10447452284). 

sorry for the inconvenience

**Comment by Schmoho** [comment]
Thanks for the information!

I will make a habit of looking at potentially existing CI pipelines before I ask build related questions.
